# Generated by Django 5.2.4 on 2025-12-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_uniq_product_name_per_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselistitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
